### ISSUE TITLE
[FEATURE] Add pagination to the page

### ISSUE THREAD

**Issue by amyyalex** [amyyalex/simple-contribution#21]
The current interface displays all objects at once, resulting in a long list as more objects are added. Introducing pagination will improve the user interface by limiting the number of objects shown per page, enhancing readability and user experience.

**Tasks:**

- Implement pagination functionality using HTML, CSS, and JavaScript.
- Design a user-friendly pagination UI element.
- Integrate pagination logic to display a set number of objects per page.
- Ensure seamless navigation between pages without affecting existing functionalities.

**Acceptance Criteria:**

- Pagination controls are visible and intuitive for users.
- Objects are displayed in a paginated manner, reducing clutter on a single page.

**Comment by oduwole-ayomipo** [comment]
Hey @amyyalex.. I really loved how you documented this issue. I would like to take this up.
