### ISSUE TITLE
Favicon not showing even though the ico file already exists in the main repo

### ISSUE THREAD

**Issue by ninja-noodle** [amyyalex/simple-contribution#225]
After getting notified that the author merged my contribution, with joy, I looked up to the simple contribution site but noticed that the favicon is not showing.
![image](https://github.com/amyyalex/simple-contribution/assets/149285885/9e8faa77-a4ef-4507-aeba-d9e674fbc481)

So I opened the dev panel and checked the resources.
**But shockingly the ico files for the favicon weren't there.**

![image](https://github.com/amyyalex/simple-contribution/assets/149285885/b67a540c-ca39-4b14-afd6-6e9638648b47)

So I thought maybe the files weren't merged to the main repo
**But when I checked, they were there which made it more confusing on why such problem happened**

![image](https://github.com/amyyalex/simple-contribution/assets/149285885/c27e9f49-d617-4c1e-bea7-03d0c1f2c051)

### Not sure if it is the GitHub deployment issue or something else but it would be better to see it fix :')
_I would also love to help fixing it if I'm needed._

**Comment by amyyalex** [comment]
Thanks for calling my attention to it. Let me have a look and see what went wrong

**Comment by ninja-noodle** [comment]
> Thanks for calling my attention to it @ninja-noodle Let me have a look and see what went wrong

I sincerely appreciate it :D Let me know if any help is required.

**Comment by amyyalex** [comment]
Hi @ninja-noodle 
@SHANLWF10 has solved this problem. The Favicon is now visible so I'll go ahead and close this issue.
Once again, thank you for your contribution.
