### ISSUE TITLE
Urgent: Template Code Issue 💔 

### ISSUE THREAD

**Issue by jeturgavli** [amyyalex/simple-contribution#252]
Hi @amyyalex ,

I accidentally deleted the template code. Should I fix it and send you a pull request, or would you prefer to handle it?

` {
      "name": "Your Name",
      "profession": "Your Profession",
      "quote": "\"Your favourite quote\"</br> - Said By Me",
      "twitter": "https://twitter.com",
      "dribbble": "https://dribbble.com",
      "behance": "https://behance.com",
      "github": "https://github.com",
      "linkedin": "https://linkedin.com",
      "email": "mailto:youremail@gmail.com"
    }`
    
    Thanks
    jeturgavli

**Comment by amyyalex** [comment]
Hi @jeturgavli 
Don't worry I've handled and fixed it from my end :)
