### ISSUE TITLE
Enhance Navbar and Card Hover Animations to Match Website Theme

### ISSUE THREAD

**Issue by yogirajbshinde21** [amyyalex/simple-contribution#254]
The current navbar lacks animations on hover and does not align with the website's theme. Additionally, the card hover effect is limited to a border color change, making it feel simplistic.

Proposed Improvements:

**1. Navbar:**
![Screenshot 2024-06-20 230924](https://github.com/amyyalex/simple-contribution/assets/84953719/0f2421d9-efc2-4d35-b411-4a00afd84c25)
- Implement hover animations for menu items.
- Style the navbar to match the website's theme.

**2. Cards:**
![Screenshot 2024-06-20 231007](https://github.com/amyyalex/simple-contribution/assets/84953719/c0a397e5-5a5c-489a-b852-64d06415ec3a)
- Introduce engaging hover effects beyond the border color change, such as shadow effects, slight zoom-ins, or background color transitions.

These enhancements will improve the visual appeal and user experience of the website.
Let me know, if I can contribute to fix this! Thank you!

**Comment by siddharthisrani** [comment]
Hii @yogirajbshinde21 can i fix this issue and work on this!

**Comment by Yashop181** [comment]
Could you assign this issue to me?

**Comment by amyyalex** [comment]
@yogirajbshinde21 Thanks for mentioning the changes that needs to be made in order to enhance the visuals of the website. Feel free to work on it if you can and also @Yashop181 and @siddharthisrani, you both can go ahead and work on it as well.
Will merge the PR that comes in first and solves the issue mentioned.
Thanks

**Comment by siddharthisrani** [comment]
Hii @amyyalex I have opened a pull request to enhance the navbar and card hover effects as mentioned. The pull request includes a screen recording demonstrating the changes. There are no conflicts, and all checks have passed.
Please review and provide feedback.

**Comment by amyyalex** [comment]
Hi @siddharthisrani 
I've reviewed and merged it. Once again, thanks for contributing.
