### ISSUE TITLE
Let's Connect button doesn't work

### ISSUE THREAD

**Issue by idk-mr4tyunjay** [amyyalex/simple-contribution#302]
**Issue Description**  
The "Let's Connect" button on the contributor's card does not currently redirect to any destination or perform any action. Ideally, this button should either:

**Expected Behavior**  
When a user clicks on the "Let's Connect" button, it should either:
1. Redirect to a single predefined link (e.g., a personal website, LinkedIn profile).
2. Display a flipped modal with social media links, allowing users to choose which platform to visit.

**Steps to Reproduce**  
1. Navigate to the contributor's card.
2. Click the "Let's Connect" button.
3. Observe that no action is taken.

**Comment by amyyalex** [comment]
Hi @idk-mr4tyunjay 
Thanks for pointing this out. I've gone ahead to solve the issue.
Thank you!
