### ISSUE TITLE
Improve the app.js file

### ISSUE THREAD

**Issue by denisakp** [amyyalex/simple-contribution#34]
Over time, the number of contributors could exceed a thousand. We should separate the Card details from the `app.js` file by creating a separate json file. So, any new contributor who wishes to add their card will do so in the json file. This would easily maintain the contents of the `app.js`.

### How to proceed ?

- Create a `cardDetails.json`file
- Move the content of `cardDetailsArray` into `cardDetails.json` file 
- Update the `cardDetailsArray` varaible so that it import `cardDetails.json`

**Comment by Wesley-waka** [comment]
I would like to be assigned the above task

**Comment by amyyalex** [comment]
Hi @Wesley-waka 
I have assigned the task to you! x

**Comment by Wesley-waka** [comment]
It's done have a look at the implementation i have made.

**Comment by amyyalex** [comment]
PR reviewed, approved and merged
Thank you for contributing! @Wesley-waka

**Comment by amyyalex** [comment]
Issue Fixed!
