### ISSUE TITLE
Implement search functionality with alphabetical sorting for names

### ISSUE THREAD

**Issue by amyyalex** [amyyalex/simple-contribution#60]
This issue aims to implement a search functionality that when a letter is keyed in, all names starting with letter shows and the results sorted alphabetically based on the entered letter. Additionally, this enhancement includes the creation of a function to sort names under the searched letter.

**Tasks:**

- Develop a search feature that accepts user input to search for names.
- Implement an alphabetical sorting function for displaying names under the searched letter.
- Create a filter mechanism to categorize names according to the searched letter.
- Integrate the search functionality with the alphabetical sorting feature.
- Perform thorough testing to ensure accurate search results and alphabetical sorting.

**Acceptance Criteria:**

- Users can input letters to search for specific names.
- Search results are sorted alphabetically and displayed under the respective searched letter.
- Names are properly indexed and categorized based on the entered letter.
- The implemented search functionality works smoothly without any glitches or errors.

**Comment by desmondezo1** [comment]
@amyyalex I would love to work on this. 

But where would the names to be fetched come from? is it an API or from a File?

**Comment by amyyalex** [comment]
Hi @desmondezo1 
Yes the names will be fetched from carddetails.json file

**Comment by DarioPrazeres** [comment]
![Captura de ecrã 2023-12-16 130451](https://github.com/amyyalex/simple-contribution/assets/87315735/44a251f1-7d24-452b-aaaf-10daa3a4902d)

I was thinking in this issues, So I can work with it. My Soluction is: the yellow rectangle is for title add your contribution and the red rectangle is for input form. Can I open this issues?

**Comment by SreekakulamLohith** [comment]
@amyyalex can you assign this issue to me.

**Comment by amyyalex** [comment]
@SreekakulamLohith This issue has already been implemented by @DarioPrazeres 
Thanks for improving it tho!

**Comment by DarioPrazeres** [comment]
So, I was navigating on the website. So, I want to implement a pagination of name. I think it will separate the names of ten or something like this ![Screenshot_20231219_151850_Chrome.jpg](https://github.com/amyyalex/simple-contribution/assets/87315735/155308f5-1933-47f8-bc68-7894518aeef5)
