### ISSUE TITLE
Enhance Readme with Dynamically Fetched Contributors' Avatars

### ISSUE THREAD

**Issue by aditya-armal** [amyyalex/simple-contribution#87]
### 🚀 Feature Proposal

Proposed Solution
Integrate a dynamic solution that fetches contributors' avatars from their GitHub profiles and displays them in the Readme. This will not only showcase the diverse community contributing to the project but also add a personal touch to the documentation.

### Motivation

Adding dynamically fetched contributors' avatars to the Readme file is not just a cosmetic enhancement; it's a visual celebration of our contributors' invaluable efforts. This addition fosters a stronger sense of community, encouraging both new and existing contributors to feel recognized and connected to the project. Let's make our Readme reflect the vibrant and diverse community that drives the success of our open-source endeavor.

### Example ( Following will be exactly added to your readme file.)

<h2>🤝 Contributors</h2>

Thanks go to these wonderful people:

<a href="https://github.com/amyyalex/simple-contribution/graphs/contributors">
  <img src="https://contrib.rocks/image?repo=amyyalex/simple-contribution" />
</a>

**Comment by Musab1258** [comment]
Hi @aditya-armal, can you assign this issue to me?
